MedicalBilling.WebMVC/Controllers/DiagnosisCodeController.cs
using MedicalBilling.Data;
using MedicalBilling.Data.Entities;
using MedicalBilling.Models.DiagnosticCodeModels;
using MedicalBilling.Services;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MedicalBilling.WebMVC.Controllers
{
    public class DiagnosisCodeController : Controller
    {
        private ApplicationDbContext _ctx = new ApplicationDbContext();

        // GET: DiagnosisCode
        [HttpGet]
        public ActionResult Index()
        {
            var service = new DiagnosticCodeService();
            var model = service.GetDiagnosticCodes();
            return View(model);
        }
        //Get DiagnosisCode List and Search
        [HttpGet]
        public ActionResult Index1(string search)
        {
            var service = new DiagnosticCodeService();
            var model = service.GetDiagnosticCodes();
            if (!String.IsNullOrEmpty(search))
            {
                model = model.Where(s => s.ICD10Code.Contains(search));
            }
            return View(model);
        }


        //Create DiagnosticCode
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(DiagnosticCodeCreate model)
        {
            var service = new DiagnosticCodeService();
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }
            service.CreateDiagnosisCode(model);
            return RedirectToAction("Index");
        }

        // GET DIAGNOSTIC CODE DETAILS/ID
        public ActionResult Details(int id)
        {
            DiagnosticCodeService service = new DiagnosticCodeService();
            var model = service.GetDiagnosticCodeById(id);
            return PartialView("Details", model);
        }


        //EDIT Diagnostic Code DETAILS
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var service = new DiagnosticCodeService();
            var detail = service.GetDiagnosticCodeById(id);
            var model = new DiagnosticCodeDetail
            {
                DiagnosticCodeId = detail.DiagnosticCodeId,
                Name = detail.Name,
                ICD10Code = detail.ICD10Code,
                Price = detail.Price,
                DiagnosisId = detail.DiagnosisId
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DiagnosticCode diagnosticCode)
        {
            if (ModelState.IsValid)
            {
                _ctx.Entry(diagnosticCode).State = EntityState.Modified;
                _ctx.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(diagnosticCode);

        }

        //DELETE diagnosticCode by ID
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            var service = new DiagnosticCodeService();
            var model = service.GetDiagnosticCodeById(id);
            return View(model);
        }
        [HttpDelete]
        public ActionResult DeleteDiagnoticCode(int id)
        {
            DiagnosticCode diagnosticCode = _ctx.DiagnosticCodes.Find(id);
            if (diagnosticCode != null) _ctx.DiagnosticCodes.Remove(diagnosticCode);
            _ctx.SaveChanges();
            return RedirectToAction("Index");
        }



    }
}

MedicalBilling.WebMVC/Controllers/DiagnosisController.cs
using MedicalBilling.Data;
using MedicalBilling.Data.Entities;
using MedicalBilling.Models.DiagnosisModels;
using MedicalBilling.Services;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MedicalBilling.WebMVC.Controllers
{

    public class DiagnosisController : Controller
    {
        private ApplicationDbContext _ctx = new ApplicationDbContext();

        // GET: LIST of Diagnosis / search
        [HttpGet]
        public ActionResult Index(string search)
        {
            var service = new DiagnosisService();
            var model = service.GetAllDiagnoses();
            if (!String.IsNullOrEmpty(search))
            {
                model = model.Where(s => s.Name.Contains(search));
            }
            return View(model);
            
        }



        //CREATE diagnosis
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(DiagnosisCreate model)
        {
            DiagnosisService service = new DiagnosisService();
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            service.CreateDiagnosis(model);
            return RedirectToAction("Index");

        }

        // GET DIAGNOSIS DETAILS/ID
        [HttpGet]
        public ActionResult Details(int id)
        {
            DiagnosisService service = new DiagnosisService();
            var model = service.GetDiagnosisById(id);
            return View(model);
        }



        //EDIT DIAGNOSIS 
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            DiagnosisService service = new DiagnosisService();
            var detail = service.GetDiagnosisById(id);
            var model = new DiagnosisDetail
            {
                DiagnosisId = detail.DiagnosisId,
                Name = detail.Name,
                Description = detail.Description,
                Symptoms = detail.Symptoms,
                Treatments = detail.Treatments
               
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Diagnosis diagnosis)
        {
            if (ModelState.IsValid)
            {
                _ctx.Entry(diagnosis).State = EntityState.Modified;
                _ctx.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(diagnosis);
        }


        //DELETE diagnosis by ID
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            DiagnosisService service = new DiagnosisService();
            var model = service.GetDiagnosisById(id);
            return View(model);
        }
        [HttpDelete]
        public ActionResult DeleteDiagnosis(int id)
        {
            DiagnosisService service = new DiagnosisService();
            service.RemoveDiagnosis(id);
            return RedirectToAction("Index");
        }
      
    }
}

MedicalBilling.WebMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MedicalBilling.WebMVC.Controllers
{
    public class HomeController : Controller
    {
        [HandleError]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

    }
}

MedicalBilling.WebMVC/Controllers/ProcedureCodeController.cs
using MedicalBilling.Data;
using MedicalBilling.Data.Entities;
using MedicalBilling.Models.ProcedureCodeModels;
using MedicalBilling.Services;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MedicalBilling.WebMVC.Controllers
{
    public class ProcedureCodeController : Controller
    {
        private ApplicationDbContext _ctx = new ApplicationDbContext();

        // GET: ProcedureCode
        [HttpGet]
        public ActionResult Index()
        {
            var service = new ProcedureCodeService();
            var model = service.GetProcedureCodes();
            return View(model);
        }
        //Get List ProcedureCode and search
        [HttpGet]
        public ActionResult Index1(string search)
        {
            var service = new ProcedureCodeService();
            var model = service.GetProcedureCodes();
            if (!String.IsNullOrEmpty(search))
            {
                model = model.Where(s => s.ICD10Code.Contains(search));
            }
            return View(model);
        }
        
        //Create ProcedureCode
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(ProcedureCodeCreate model)
        {
            var service = new ProcedureCodeService();
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }
            service.CreateProcedureCode(model);
            return RedirectToAction("Index");
        }

        // GET ProcedureCode DETAILS/ID
        public ActionResult Details(int id)
        {
           
            var service = new ProcedureCodeService();
            var model = service.GetProcedureCodeById(id);
            return PartialView("Details", model);
        }


        //EDIT ProcedureCode DETAILS
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {

            var service = new ProcedureCodeService();
            var detail = service.GetProcedureCodeById(id);
            var model = new ProcedureCodeDetail
            {
                ProcedureCodeId = detail.ProcedureCodeId,
                Name = detail.Name,
                ICD10Code = detail.ICD10Code,
                Price = detail.Price,
                ProcedureId = detail.ProcedureId
            };
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(ProcedureCode procedureCode)
        {
            if (ModelState.IsValid)
            {
                _ctx.Entry(procedureCode).State = EntityState.Modified;
                _ctx.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(procedureCode);
        }

        //DELETE procedureCode by ID
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            var service = new ProcedureCodeService();
            var model = service.GetProcedureCodeById(id);
            return View(model);
        }
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteProcedureCode(int id)
        {
            ProcedureCode procedureCode = _ctx.ProcedureCodes.Find(id);
            if (procedureCode != null) _ctx.ProcedureCodes.Remove(procedureCode);
            _ctx.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

MedicalBilling.WebMVC/Controllers/ProcedureController.cs
using MedicalBilling.Data;
using MedicalBilling.Data.Entities;
using MedicalBilling.Models.ProcedureModel;
using MedicalBilling.Services;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MedicalBilling.WebMVC.Controllers
{
    public class ProcedureController : Controller
    {
        private ApplicationDbContext _ctx = new ApplicationDbContext();

        // GET: Procedure
        [HttpGet]
        public ActionResult Index(string search)
        {
            var service = new ProcedureService();
            var model = service.GetProcedures();
            if (!String.IsNullOrEmpty(search))
            {
                model = model.Where(s => s.Name.Contains(search));
            }
            return View(model);
        }


        //Create Procedure
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(ProcedureCreate model)
        {
            var service = new ProcedureService();
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            service.CreateProcedure(model);
            return RedirectToAction("Index");
        }

        // GET Procedure DETAILS/ID
        [HttpGet]
        public ActionResult Details(int id)
        {
            var service = new ProcedureService();
            var model = service.GetProcedureById(id);
            return View(model);
        }


        //EDIT Procedure DETAILS
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var service = new ProcedureService();
            var detail = service.GetProcedureById(id);
            var model = new ProcedureDetail
            {
                ProcedureId = detail.ProcedureId,
                Name = detail.Name,
                Description = detail.Description,
                Preperation = detail.Preperation,
                Risks = detail.Risks
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Procedure procedure)
        {
            if (ModelState.IsValid)
            {
                _ctx.Entry(procedure).State = EntityState.Modified;
                _ctx.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(procedure);
        }

        //DELETE Procedure by ID
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            ProcedureService service = new ProcedureService();
            var model = service.GetProcedureById(id);
            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        { 
            Procedure procedure = _ctx.Procedures.Find(id);
           if(procedure != null) _ctx.Procedures.Remove(procedure);
            _ctx.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

MedicalBilling.WebMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}


<h1>About</h1>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h3>What we offer</h3>
            <p>
                MedicalBillingCode is transforming the healthcare experiance with the most powerful, easy to use, flexiable resource for all users.
                We provide public users the ability to find diagnostic codes(ICD-10) to determin pricing of diagnoses and procedures.
                We want you to be ready before you get that bill from your provider.
            </p>
        </div>
        <div class="col-md-4">
            <h3>Our Mission</h3>
            <p>
                MedicalBillingCode believes that healthcare deserves tools that are as modern, well-designed, and easy-to-use as the ones encountered elsewhere in our daily lives.
                Our mission, therefore, is to re-platform healthcare with modern, source-based solutions. To provide patients and consumers with the medical source in improving their lives.
            </p>
        </div>
    </div>
</div>

MedicalBilling.WebMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MedicalBilling.WebMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";

    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/bootstrap")
}
       
   <div class="wrapper">
    <div class="top">
        <div class="search-header">
            <h1>Look Up ICD-10 Code</h1>
            <p>Search a diagnosis or procedure to obtain Medical ICD-10 codes</p>
        </div>
    
        <div class="row">
            <div class="col-lg-offset-1 col-lg-10">
                <div style="padding-bottom:30px">
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#dx-tab" aria-controls="dx-tab" role="tab" data-toggle="tab">Diagnosis</a>
                        </li>
                        <li>
                            <a href="#px-tab" aria-controls="px-tab" role="tab" data-toggle="tab"><span class="hidden-sm hidden-xs">Procedure</span></a>
                        </li>
                        <li>
                            <a href="#cs-tab" aria-controls="cs-tab" role="tab" data-toggle="tab"><span class="hidden-sm hidden-xs">ICD10-CMS Code</span></a>
                        </li>
                        <li>
                            <a href="#ps-tab" aria-controls="ps-tab" role="tab" data-toggle="tab"><span class="hidden-sm hidden-xs">ICD10-PCS Code</span></a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" id="dx-tab">
                            @using (Html.BeginForm("Index", "Diagnosis", FormMethod.Get))
                            {
                                <div class="input-group input-group-lg">
                                    <input type="search" id="dx" name="search" class="form-control" value="" placeholder="ie: Diabetes">
                                    <div class="input-group-btn">
                                        <button type="submit" class="btn btn-primary"><span class="hidden-xs">Search</span><span class="glyphicon glyphicon-search small visible-xs"></span></button>
                                    </div>
                                </div>
                            }
                        </div>

                        <div role="tabpanel" class="tab-pane" id="px-tab">
                            @using (Html.BeginForm("Index", "Procedure", FormMethod.Get))
                            {
                                <div class="input-group input-group-lg">
                                    <input type="search" id="px" name="search" class="form-control" value="" placeholder="ie: Appendectomy">
                                    <div class="input-group-btn">
                                        <button type="submit" class="btn btn-primary"><span class="hidden-xs">Search</span><span class="glyphicon glyphicon-search small visible-xs"></span></button>
                                    </div>
                                </div>
                            }
                        </div>

                        <div role="tabpanel" class="tab-pane" id="cs-tab">
                            @using (Html.BeginForm("Index1", "DiagnosisCode", FormMethod.Get))
                            {
                                <div class="input-group input-group-lg">
                                    <input type="search" id="cs" name="search" class="form-control" value="" placeholder="ie: F41.0">
                                    <div class="input-group-btn">
                                        <button type="submit" class="btn btn-primary"><span class="hidden-xs">Search</span><span class="glyphicon glyphicon-search small visible-xs"></span></button>
                                    </div>
                                </div>
                            }
                        </div>

                        <div role="tabpanel" class="tab-pane" id="ps-tab">
                            @using (Html.BeginForm("Index1", "ProcedureCode", FormMethod.Get))
                            {
                                <div class="input-group input-group-lg">
                                    <input type="search" id="ps" name="search" class="form-control" value="" placeholder="ie: F41.0">
                                    <div class="input-group-btn">
                                        <button type="submit" class="btn btn-primary"><span class="hidden-xs">Search</span><span class="glyphicon glyphicon-search small visible-xs"></span></button>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
     </div>




        <div class="container" style="margin-top:4em;">
            <div class="row">
                <div class="col-md-4">
                    <h3>ICD-10 INFORMATION</h3>
                    <p>
                        ICD (International Statistical Classification of Diseases and Related Health problems) is now on its 10th revision. ICD-10 codes are the byproduct of that revision.
                        This medical classification list is generated by the World Health Organization (WHO), and is used to help healthcare providers identify and code health conditions.
                    <p>

                    <p>ICD-10 is required for use by physicians and healthcare providers under the Health Insurance Portability & Accountability Act (HIPAA) and will replace all ICD-9 code sets.</p>

                    <p>
                        Many more new diagnoses can be tracked using ICD-10 than with ICD-9. Some expanded code sets, like ICD-10-CM, have over 70,000 codes.
                    </p>
                </div>
                <div class="col-md-4">
                    <h3>What we offer</h3>
                    <p>
                        MedicalBillingCode is transforming the healthcare experiance with the most powerful, easy to use, flexiable resource for all users.
                        We provide public users the ability to find diagnostic codes(ICD-10) to determin pricing of diagnoses and procedures.
                        We want you to be ready before you get that bill from your provider.
                    </p>
                </div>
                <div class="col-md-4">
                    <h3>Our Mission</h3>
                    <p>
                        MedicalBillingCode believes that healthcare deserves tools that are as modern, well-designed, and easy-to-use as the ones encountered elsewhere in our daily lives.
                        Our mission, therefore, is to re-platform healthcare with modern, source-based solutions. To provide patients and consumers with the medical source in improving their lives.
                    </p>
                </div>
            </div>
        </div>
        <br />
        <br />
        <br />
        <br />
       </div>